-- DG BHAI 9X analytics schema for Supabase
create table if not exists public.landing_visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text,
  fingerprint text,
  ip_hash text,
  ref text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  landing_page text,
  referrer text,
  user_agent text,
  screen_width integer,
  screen_height integer,
  timezone text
);

create table if not exists public.telegram_clicks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text,
  fingerprint text,
  ip_hash text,
  ref text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  landing_page text,
  referrer text,
  user_agent text,
  dwell_seconds integer default 0,
  classification text not null default 'likely_real',
  reasons jsonb not null default '[]'::jsonb
);

create index if not exists landing_visits_created_at_idx on public.landing_visits(created_at desc);
create index if not exists landing_visits_fingerprint_idx on public.landing_visits(fingerprint);
create index if not exists landing_visits_ref_idx on public.landing_visits(ref);
create index if not exists telegram_clicks_created_at_idx on public.telegram_clicks(created_at desc);
create index if not exists telegram_clicks_fingerprint_idx on public.telegram_clicks(fingerprint);
create index if not exists telegram_clicks_ref_idx on public.telegram_clicks(ref);

alter table public.landing_visits enable row level security;
alter table public.telegram_clicks enable row level security;

-- No public policies are created. The Vercel API uses the server-side
-- service-role key, which must never be exposed to the browser.
